name: flutter-android-build
description: 'ðŸ— Easy to use flutter android build action'
author: NiklasLehnfeld
branding:
  icon: 'zap'
  color: 'black'

inputs:
  release:
    description: 'If set to `true`, it will run release builds, otherwise debug builds'
    required: false
    default: false
  build-type:
    description: 'apk | aab | both'
    required: false
    default: both
  keystore:
    description: 'Base64 encoded keystore.jks, required if release is true'
    required: false
    default: ''
  keystore-pwd:
    description: 'keystore password, required if release is true'
    required: false
    default: ''
  key-pwd:
    description: 'key password, required if release is true'
    required: false
    default: ''
  flavor:
    required: false
    default: ''
    description: 'flavor for build'

outputs:
  apk-path:
    description: "Path to built apk if build-type was set to apk or both"
    value: ${{ steps.path-output.outputs.apk-path }}
  aab-path:
    description: "Path to built aab if build-type was set to aab or both"
    value: ${{ steps.path-output.outputs.aab-path }}

runs:
  using: "composite"
  steps:
    - run: flutter pub get
      shell: bash
    - run: flutter pub run build_runner build --delete-conflicting-outputs
      shell: bash
    - run: echo "${{ inputs.keystore }}" | base64 -d > android/keystore.jks
      shell: bash
    - env:
        KEY_PWD: ${{ inputs.key-pwd }}
        KEYSTORE_PWD: ${{ inputs.keystore-pwd }}
      run: |
        FLAVOR_OPTIONS=""
        if [ -n "${{ inputs.flavor }}" ]; then
          FLAVOR_OPTIONS="--flavor=${{ inputs.flavor }} --dart-define=app.flavor=${{ inputs.flavor }}"
        fi

        if [ ${{ inputs.release }} = "true" ]; then

          if [ ${{ inputs.build-type }} = "apk" ] || [ ${{ inputs.build-type }} = "both" ]; then
            flutter build apk $FLAVOR_OPTIONS || true
          fi
          if [ ${{ inputs.build-type }} = "aab" ] || [ ${{ inputs.build-type }} = "both" ]; then
            flutter build appbundle $FLAVOR_OPTIONS || true
          fi

        else

          if [ ${{ inputs.build-type }} = "apk" ] || [ ${{ inputs.build-type }} = "both" ]; then
            flutter build apk --debug $FLAVOR_OPTIONS || true
          fi
          if [ ${{ inputs.build-type }} = "aab" ] || [ ${{ inputs.build-type }} = "both" ]; then
            flutter build appbundle --debug $FLAVOR_OPTIONS || true
          fi
        fi
      shell: bash
    - run: |
        BUILD_OUTPUT_PATH="build/app/outputs"
        if [ -n "${{ inputs.flavor }}" ]; then
          APK_DEBUG_PATH="$BUILD_OUTPUT_PATH/apk/${{ inputs.flavor }}/debug"
          APK_RELEASE_PATH="$BUILD_OUTPUT_PATH/apk/${{ inputs.flavor }}/release"
          AAB_DEBUG_PATH="$BUILD_OUTPUT_PATH/bundle/${{ inputs.flavor }}Debug"
          AAB_RELEASE_PATH="$BUILD_OUTPUT_PATH/bundle/${{ inputs.flavor }}Release"
        else
          APK_DEBUG_PATH="$BUILD_OUTPUT_PATH/apk/debug"
          APK_RELEASE_PATH="$BUILD_OUTPUT_PATH/apk/release"
          AAB_DEBUG_PATH="$BUILD_OUTPUT_PATH/bundle/debug"
          AAB_RELEASE_PATH="$BUILD_OUTPUT_PATH/bundle/release"
        fi

        if [ ${{ inputs.release }} = "true" ]; then

          if [ ${{ inputs.build-type }} = "apk" ] || [ ${{ inputs.build-type }} = "both" ]; then
            APK_PATH="$APK_RELEASE_PATH/$(ls $APK_RELEASE_PATH | grep apk)"
            if [ ! -f $APK_PATH ]; then
              exit 1
            fi
            echo "::set-output name=apk-path::$(echo $APK_PATH)"
          fi

          if [ ${{ inputs.build-type }} = "aab" ] || [ ${{ inputs.build-type }} = "both" ]; then
            AAB_PATH="$AAB_RELEASE_PATH/$(ls $AAB_RELEASE_PATH | grep aab)"
            if [ ! -f $AAB_PATH ]; then
              exit 1
            fi
            echo "::set-output name=aab-path::$(echo $AAB_PATH)"
          fi

        else

          if [ ${{ inputs.build-type }} = "apk" ] || [ ${{ inputs.build-type }} = "both" ]; then
            APK_PATH="$APK_DEBUG_PATH/$(ls $APK_DEBUG_PATH | grep apk)"
            if [ ! -f $APK_PATH ]; then
              exit 1
            fi
            echo "::set-output name=apk-path::$(echo $APK_PATH)"
          fi

          if [ ${{ inputs.build-type }} = "aab" ] || [ ${{ inputs.build-type }} = "both" ]; then
            AAB_PATH="$AAB_DEBUG_PATH/$(ls $AAB_DEBUG_PATH | grep aab)"
            if [ ! -f $AAB_PATH ]; then
              exit 1
            fi
            echo "::set-output name=aab-path::$(echo $AAB_PATH)"
          fi
        fi
      shell: bash
      id: path-output
